const EMPLOYMENT__ADD = 'EMPLOYMENT__ADD';
const EMPLOYMENT__REMOVE = 'EMPLOYMENT__REMOVE';
const EMPLOYMENT__START_DATE = 'EMPLOYMENT__START_DATE';
const EMPLOYMENT__END_DATE = 'EMPLOYMENT__END_DATE';
const EMPLOYMENT__COMPANY = 'EMPLOYMENT__COMPANY';
const EMPLOYMENT__POSITION = 'EMPLOYMENT__POSITION';
const EMPLOYMENT__TOOLS = 'EMPLOYMENT__TOOLS';
const EMPLOYMENT__SUMMARY = 'EMPLOYMENT__SUMMARY';

export {
  EMPLOYMENT__ADD,
  EMPLOYMENT__REMOVE,
  EMPLOYMENT__START_DATE,
  EMPLOYMENT__END_DATE,
  EMPLOYMENT__COMPANY,
  EMPLOYMENT__POSITION,
  EMPLOYMENT__TOOLS,
  EMPLOYMENT__SUMMARY
};
