const TECHNOLOGY__ADD = 'TECHNOLOGY__ADD';
const TECHNOLOGY__REMOVE = 'TECHNOLOGY__REMOVE';
const TECHNOLOGY__NAME = 'TECHNOLOGY__NAME';
const TECHNOLOGY__PROFICIENCY = 'TECHNOLOGY__PROFICIENCY';

export {
  TECHNOLOGY__ADD,
  TECHNOLOGY__REMOVE,
  TECHNOLOGY__NAME,
  TECHNOLOGY__PROFICIENCY
};
