const PERSONAL__ADD = 'PERSONAL__ADD';
const PERSONAL__REMOVE = 'PERSONAL__REMOVE';
const PERSONAL__NAME = 'PERSONAL__NAME';
const PERSONAL__TEXT = 'PERSONAL__TEXT';

export {
  PERSONAL__ADD,
  PERSONAL__REMOVE,
  PERSONAL__NAME,
  PERSONAL__TEXT
};
