const TOOL__ADD = 'TOOL__ADD';
const TOOL__REMOVE = 'TOOL__REMOVE';
const TOOL__NAME = 'TOOL__NAME';
const TOOL__PROFICIENCY = 'TOOL__PROFICIENCY';

export {
  TOOL__ADD,
  TOOL__REMOVE,
  TOOL__NAME,
  TOOL__PROFICIENCY
};
