const EDUCATION__ADD = 'EDUCATION__ADD';
const EDUCATION__REMOVE = 'EDUCATION__REMOVE';
const EDUCATION__START_DATE = 'EDUCATION__START_DATE';
const EDUCATION__END_DATE = 'EDUCATION__END_DATE';
const EDUCATION__INSTITUTION = 'EDUCATION__INSTITUTION';
const EDUCATION__COUNTRY = 'EDUCATION__COUNTRY';
const EDUCATION__CITY = 'EDUCATION__CITY';

export {
  EDUCATION__ADD,
  EDUCATION__REMOVE,
  EDUCATION__START_DATE,
  EDUCATION__END_DATE,
  EDUCATION__INSTITUTION,
  EDUCATION__COUNTRY,
  EDUCATION__CITY
};
