const NETWORK__ADD = 'NETWORK__ADD';
const NETWORK__REMOVE = 'NETWORK__REMOVE';
const NETWORK__NAME = 'NETWORK__NAME';
const NETWORK__LINK = 'NETWORK__LINK';

export {
  NETWORK__ADD,
  NETWORK__REMOVE,
  NETWORK__NAME,
  NETWORK__LINK
};
